### ISSUE TITLE
[Bug] Moving falling blocks

### ISSUE THREAD

**Issue by SylisMC** [haubna/PhysicsMod#116]
When blocks fall the block break particle play and I'm not sure if this is intentional. but it does look kinda weird

**Comment by SylisMC** [comment]
(AKA Sand, gravel, redsand)

**Comment by haubna** [comment]
Yeah, haven't found a solution to this problem yet.

**Comment by SylisMC** [comment]
Hmm
Could you...
A) Do a check for a player breaking the block before triggering the particles?
B) Check for a falling block entity before triggering the particles?
C) Trigger sand, gravel, & Redsand particles only if the item entity is detected?
D) make falling block entities kill particles in its path rather than collide with them

Im sure you've probably thought of that already but maybe not

**Comment by Shosis0** [comment]
is it still not solved?

**Comment by haubna** [comment]
Will be fixed with Pro v167 finally, the solution for anyone curious was basically 
1. keeping track of all falling block entities that got added
2. when a block update happens that could trigger client physics just discard it when a falling block entity has the same starting position (this was the key point, I wasn't aware that a falling block entity actually has the starting position saved and sent to the client)
