### ISSUE TITLE
Physics Settings button overlapping other buttons when using the Bounding Box Outline Reloaded mod [BUG]

### ISSUE THREAD

**Issue by elhertz** [haubna/PhysicsMod#167]
**Describe the bug**
The `Physics Settings` button is overlapping the `Skin Customization` and `Music & Sounds` button when [Bounding Box Outline Reloaded](https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded) is also installed

**To Reproduce**
Install the mod on Fabric 1.17.1 using the latest version of Physics Settings on curseforge and [Bounding Box Outline Reloaded](https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded).

**Screenshots**
![example1](https://i.imgur.com/Ksv9i1A.png)
![example2](https://i.imgur.com/olbjSHY.png)

BBOR uninstalled:
![example3](https://i.imgur.com/0vC5MWz.png)

Minecraft Version: 1.17.1
Physics Mod Version: Physics 2.5.13
Bounding Box Outline Reloaded: BBOutlineReloaded-2.4-1.17.1-fabric-beta2.jar

edit: Added BBOR version

**Comment by CypherXG** [comment]
I have no BBOR installed and the same Error.
So i think it has nothing to do with BBOR.
Here its overlapping with my Myst Mod addon.
Is it possible to make the Button smaler because all Buttons have the same size

![2024-01-15_18 35 58](https://github.com/haubna/PhysicsMod/assets/7895130/81f80cf2-99a4-4d51-baa1-143247bc79f6)

**Comment by haubna** [comment]
With the latest snapshot 24w09a Minecraft uses some proper layouts (instead of hardcoded coordinates). In this version and going forward it gets added into the grid layout which should eliminate that bug. Unfortunately for prior versions that have overlapping buttons it is best to access each mod settings via the Mod Menu.
