### ISSUE TITLE
No texture [BUG]

### ISSUE THREAD

**Issue by Medatur76** [haubna/PhysicsMod#172]
**Describe the bug**
I know last time I didn't have an error and i was just confused but now I do. The enderpearl and snowball have no texture when I throw them. I tryed removing and adding my shaders and texture packs but not use

**To Reproduce**
Run 1.17.1 with the mod and optifabric and optifine

**Screenshots**
![EnderPearl](https://user-images.githubusercontent.com/90143210/137818377-8bd629d8-afa4-4179-af69-2704487f5560.png)

![Snowball](https://user-images.githubusercontent.com/90143210/137818407-3395a338-a73a-4512-9ecf-9054f2719084.png)

Minecraft Version: 1.17.1
Physics Mod Version: 16v

**Comment by haubna** [comment]
What I've found out is that it indeed is a optifine bug. My game also crashes when not using the physics mod and just optifine/optifabric and using certain resource packs. The only thing that I can recommend is to use the Iris Shader mod.

Update: Turns out this bug doesn't exist with the Forge version and Optifine. My best guess is that optifabric introduces some kind of bug.

**Comment by Medatur76** [comment]
also, I tryed this at first with my custom texturepack and the same, so its not the texture packs, maby the shaders ig

**Comment by Medatur76** [comment]
So, the texture somehow fixed emself but the shater/bounce/disaper wont work

**Comment by haubna** [comment]
Fixed.
