### ISSUE TITLE
Large stuttering/microcrashes [BUG]

### ISSUE THREAD

**Issue by 1Mercenary** [haubna/PhysicsMod#233]
**Describe the bug**
Whilst underground or within certain biomes of the nether (currently only known with the Basalt Deltas) I am getting large amounts of stuttering and micro crashes. I've attached a .log to the issue as I honestly have no idea of whats happening other than what is within it. This started on a new Hypixel SMP server, so basically a vanilla mc 1.18 server. I'm using your latest liquid beta pro physics mod version.

**To Reproduce**
travel towards the basalt deltas within the nether or dig underground (deep slate layers) within the overworld.

Minecraft Version: 1.18
Physics Mod Version: Physics-Mod-Pro-V23
[latest.log](https://github.com/haubna/PhysicsMod/files/7785779/latest.log)

Scroll to the bottom of the log to see the errors that brought me to you.

**Comment by haubna** [comment]
Those are no crashes. Just happens when it creates the physics from certain entities. I will spare you the details. What probably happens is that there is gravel falling which triggers the block physics. The newest version Pro V24 and upwards have a block physics activation range. So that your physics don't get triggered when there is gravel falling at the other end of the map. That should improve your performance hopefully.
