### ISSUE TITLE
5 Vine Physics Enhancements

### ISSUE THREAD

**Issue by TheFastRunners** [haubna/PhysicsMod#252]
1. Fixed Point For Both Ends Of Vines At Once. Replaces the fixed on bottom button with a button that cycles through the different options (fixed on top, bottom, or both).
2. Vine Range. A slider changing how many blocks in distance for blocks that can be attached to vines can connect adjacently to each other (Example: Collapsing Trees).
3. Multi-Block Connection. Set multiple blocks to be able to connect to vines (Example: Chains with either Lanterns or Soul Lanterns attached)
4. Collapsing Vines. When enabled, makes the vine collapse when broken like with block collapsing or when breaking bamboo/scaffolding. (Server Setting)
5. Sideways Vines. Makes Blocks that can connect to walls from the sides (like chains) able to have vine physics.

**Comment by danieljross** [comment]
+1 on this.

Chains that appear in mineshafts have always bothered me since they don't connect to the fence posts on the walkways.

You could always add oak fences as blocks that can connect to chains, but then they become free to swing around, even if you make their hitbox as small as possible. Choosing to instead have the fences fixed to the ground causes the chains to fall over. Neither is ideal.

Support for two fixed points would be great. Just thought I'd add this comment as a real-world example of why these 5 suggestions are important.

**Comment by haubna** [comment]
Closed due to moving feature suggestions to the [discord](https://discord.gg/VsNs9xP) (channel #feature-suggestions)
