### ISSUE TITLE
PRO Version is EULA violation

### ISSUE THREAD

**Issue by Minecraftschurli** [haubna/PhysicsMod#305]
The nature of this mod locking content behind a PRO version is a violation of the Minecraft EULA. Early access or cosmetics for supporters are allowed but locking content behind a paywall is a violation of the EULA. This is just to inform you about the situation so that you know before someone reports this mod.

**Comment by KajeArch** [comment]
Since the author silently closed this issue, this can be understood as a refusal to cooperate, which is unfortunate. I would like to request for the author of this mod to cooperate and clarify this issue. Now. Otherwise I will have to file a report for the "Pro" version of this mod to Mojang. This should not be understood as an act of hostility, but as an act of equality. My colleagues who mod Minecraft themselves are quite outraged that someone is making money here with charging of a mod that is strictly forbidden under the Minecraft EULA. While other modders have to beg for donations, here a Pro version of this mod is hidden behind a paywall from which the author of this mod draws profit, illegally. I would like the author to participate in this discussion. 

Citing the relevant sections of the EULA to add to this discussion: 
https://www.minecraft.net/en-us/terms#terms-commercial_guidelines
@haubna 

> If you buy, download, **use** or play our Game, you are agreeing to stick to the rules of these end user license agreement ("EULA") terms. If you don't want to or can't agree to these rules, then you must not buy, download, use or play our Game. This EULA incorporates the terms of use for the mojang.com website ("Account Terms"), our brand and asset usage guidelines, our privacy policy, and, if you live in the United States, our Arbitration Agreement. By agreeing to this EULA you also agree to all of the terms of the foregoing documents, so please read through them carefully.

> Extended Functionality and “Mods”
> If you comply with and follow the Essential Requirements (in the Brand and Asset Usage Guidelines) and Naming Guidelines above, YOU MAY distribute or make available plug-ins and other bits and pieces of extended functionality etc. that you create (together, "Mods") **for free** and **without any charge**, but not if the purpose of your Mod is to advertise or promote other products or services (see the section below on Building Promotions with Minecraft). By "Mods," we mean something original that you created that doesn't contain a substantial part of our copyrightable code or content. **We have the final say** on what constitutes a Mod and what doesn't. When you combine your Mod with the Minecraft software, we will call that combination a "Modded Version" of the Game. You MAY NOT distribute any Modded Versions of our Game or software, though you may distribute Mods. You may make money from Mods as described below in the section, "Servers and Hosting."

> Servers and Hosting

> With hosting servers, we want to enable the community to make money by creating, hosting, and maintaining servers for Minecraft, so you may do this subject to these Guidelines. By "server," we mean a single connecting address or IP number.

> Therefore, if you comply with and follow the Brand and Asset Usage Guidelines and Naming Guidelines above, YOU MAY:
>
-     charge for access to your server, including a server which hosts your Mods, BUT only if:
-         you make a charge per person that is the same for everyone;
-         you give everyone you charge access to all the Mods that you choose to have on your server (except only in respect of genuine admin tools / admin Mods which should be reserved to administrators);
-         you only give access to your server to users who have a genuine paid for version of Minecraft;
-         you own or control the server and continue to do so for the whole time that you charge for access to it - so, if you sell the actual servers or server space with Mods pre-installed on them, you must ensure that the person buying the server is aware that she must follow these rules. Essentially you can’t get around the above by setting up servers with Mods on and then selling those set-ups
-     **ask for donations (as opposed to direct charges) IF you do not offer the individual donor something in exchange that only he or she can use.** You may offer server wide rewards if donation goals are achieved though.

Again, the Pro version is a clear violation of the EULA. If the owner does not want to participate in this discussion, we will have to report this mod, because I deem it highly unfair to other modders, including myself, who have to genuinely ask for donations without giving core functionality in exchange (like the EULA says) while this guy here just leeches off money from a copyrighted game illegally.
