### ISSUE TITLE
How do i install this mod in iris?

### ISSUE THREAD

**Issue by Matteo8961** [haubna/PhysicsMod#319]

**Comment by NaiNonTH** [comment]
You can't install this mod in Iris alone. You will need [Fabric Loader](https://fabricmc.net/use/installer/) and [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-apihttps://www.curseforge.com/minecraft/mc-mods/fabric-api) in order to install [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodiumhttps://www.curseforge.com/minecraft/mc-mods/sodium)*, [Iris](https://www.curseforge.com/minecraft/mc-mods/irisshadershttps://www.curseforge.com/minecraft/mc-mods/irisshaders), and Physics Mod.

Note: * You need to install Sodium along with Iris to make them work together, for better performance.
