### ISSUE TITLE
Fish heads super detached from body with Ragdoll selecetd

### ISSUE THREAD

**Issue by jacobc62** [haubna/PhysicsMod#323]
So I was originally going to place a bug report about how despite not having any mods that change vanilla mods, the ragdoll physics was acting like the fractured physics instead. Turns out the ragdoll physics are working fine on most mobs, however for the fish mobs (Cod and Salmon specifically), it appears that the head becomes super detached from the rest of the body upon death, leading to odd sights involving fish heads being about 4-5 meters in the air if you happen to get the angle right on the body on the ground.

Minecraft Version: 1.18.2
Physics Mod Version: Forge 2.6.9

**Comment by haubna** [comment]
My first guess is that you are using Optifine and some kind of Resource Pack that uses CEM (custom entity models). There is no way I can create ragdolls on the fly for custom entity models. Let me know if this problem persists without any resource pack and CEM. Whenever it fails to create the Ragdoll due to some error it defaults back to the blocky configuration.

**Comment by haubna** [comment]
Fixed with 2.11.6 (in case it was Optifine related, CEM models will not work).
