### ISSUE TITLE
Multiplayer menu says incompatible with forge server

### ISSUE THREAD

**Issue by ghost** [haubna/PhysicsMod#391]
please make this not required on server-side its confusing for clients trying to join a forge server to be told its incompatible, I know some parts of the mod work server-side but I am thinking about clients who just use ragdoll client-side for example and have other things disabled

[12Jul2022 22:30:28.751] [Netty Client IO/INFO] [net.minecraftforge.client.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [physicsmod]

**Comment by haubna** [comment]
Oh yeah, I totally forgot that that was even a thing (I started development on Fabric). It will be fixed in the next version. In the mean time you should be able to fix this by opening the mod .jar and adding 'displayTest="IGNORE_ALL_VERSION"' in the META-INF/mods.toml file below '[[mods]] #mandatory'. I will close this issue once the update is released.

**Comment by haubna** [comment]
Should be fixed in the latest version.
