### ISSUE TITLE
Entity ragdolls and "deaths" + Block obstruction

### ISSUE THREAD

**Issue by ohnecksThing** [haubna/PhysicsMod#6]
I'm impressed by the possibilities of the mod, but there's few things that I don't quite work as intended. Like, armor stand has no ragdoll physics and just crashes the game, some mobs have no ragdoll mode as well but instead are just falling apart like wither and iron golem (Blocky mode instead). Is that, perhaps, possible to fix? Minecraft version: 1.16.5. Also, some entities are crashing in pieces just because they're entering blocks (bees entering hives, silverfishes hiding in stone blocks and parrots sitting on your shoulders, at most), which is... well, just a little bit weird, I dunno.
Also, will there be options what blocks specifically can be obstructed by the surrounding blocks? That mod is pretty useful as the tree capitator replacer, but it also capitates... everything else. Just one block, and half of a hill just gets ruined in touch. My idea is if we could limit the game to obstruct only certain blocks?

**Comment by haubna** [comment]
Not all mobs support ragdoll physics. Armor stand crash should be fixed in the next release (in 1.17, 1.16.5 is a old version of Minecraft and is no longer supported). Mobs disappearing into blocks and causing physics is unluckily impossible to fix since the client doesn't know that it enters a block.

Collapsing block physics will get more features once I am happy with the basic physics.

**Comment by ohnecksThing** [comment]
Alrighty then, got it, thanks for the response!
