### ISSUE TITLE
Water rendering slowly only high end device with ocean physics enabled?

### ISSUE THREAD

**Issue by AnarchyBlues** [haubna/PhysicsMod#708]
**Describe the bug**
Water takes a long time to render when ocean physics are enabled. After loading into the game it takes between 20 - 25 seconds for the water to actually render. I've tried it both with and without optimization mods like Sodium and it doesn't seem to make a difference. Neither does re-loading the map or loading from a fresh boot.

Specs for reference:
- CPU: R9 5900X
- GPU: RTX 4070 Ti
- SSD: Samsung 980 Pro 2TB
- RAM: 128GB (MC is allowed 20GB)
- Windows 10 64bit

**To Reproduce**
Load into the game.

**Screenshots**
![image](https://github.com/haubna/PhysicsMod/assets/98670485/9a6b5d3c-b73f-4443-ac60-8cebffcf5403)

Minecraft Version: 1.20.1 (using Prism)
Physics Mod Version: physics-mod-pro-v155-fabric-1.20

**Comment by MalevolentWulf** [comment]
What is your chunk render distance set for? I find it struggles to load consistently with anything beyond 14.

**Comment by Verequies** [comment]
I can confirm this issue. At any chunk render distance it seems to low quite slowly - instant when Ocean Physics is off. It does take significantly longer on larger chunk distances and can take up to a minute before the water properly renders. Using a mod such as Xaeros World Map or alt-tabbing for a time makes the water disappear and takes just as long to re-render.

I've currently got an i5 10500, an RX 6950 XT (Odd combination I know)  and 64 GB of RAM running on Arch Linux. This was tested with Physics Mod Pro v157 on Fabric.

**Comment by haubna** [comment]
It has to compute way more for the ocean physics. This is not a bug just a computation limit.

**Comment by Verequies** [comment]
@haubna, true it is an expensive computational operation. However this does not explain why alt-tabbing and using your desktop for a time before coming back to Minecraft, or say looking around Xaeros World Map for a couple minutes and then returning essentially makes the oceans disappear and the ocean physics have to be recomputed.  I believe this would be the same for any other menu that is full screen and does not require Minecraft to render the world (as I have seen this in some menus).

On the computation front, perhaps the computation speed/time could be improved. Maybe you could use a library such as OpenBLAS/BLAS or Intel's OneMKL?

To me it seems like it ways for a bit after the all the chunks have loaded in (depends on the render distance) before it finishes calculating the ocean physics. Instead it could render the water chunk by chunk as it does when using vanilla Minecraft.

Regardless of render speed, I am fairly sure most of the time the chunks are going to look the same when you load the world. The ocean physics could have an optional caching mechanism so that it does the computation on the first load per chunk and then the next time the world is loaded it reads the cache and continues on if necessary. There could be a command line option to invalidate certain chunks if they need recomputing for some reason, to which it would just used the cached values of the surrounding chunks to help compute.

I would be more than happy to try a few things out code wise if you would like an extra set of eyes.
